import { IRC_FIELD_LABELS } from "./schema.irc.js";

export const FIELD_LABELS: Record<string, string> = {
  "meta.lastTouchedVersion": "Config Last Touched Version",
  "meta.lastTouchedAt": "Config Last Touched At",
  "update.channel": "Update Channel",
  "update.checkOnStart": "Update Check on Start",
  "diagnostics.enabled": "Diagnostics Enabled",
  "diagnostics.flags": "Diagnostics Flags",
  "diagnostics.otel.enabled": "OpenTelemetry Enabled",
  "diagnostics.otel.endpoint": "OpenTelemetry Endpoint",
  "diagnostics.otel.protocol": "OpenTelemetry Protocol",
  "diagnostics.otel.headers": "OpenTelemetry Headers",
  "diagnostics.otel.serviceName": "OpenTelemetry Service Name",
  "diagnostics.otel.traces": "OpenTelemetry Traces Enabled",
  "diagnostics.otel.metrics": "OpenTelemetry Metrics Enabled",
  "diagnostics.otel.logs": "OpenTelemetry Logs Enabled",
  "diagnostics.otel.sampleRate": "OpenTelemetry Trace Sample Rate",
  "diagnostics.otel.flushIntervalMs": "OpenTelemetry Flush Interval (ms)",
  "diagnostics.cacheTrace.enabled": "Cache Trace Enabled",
  "diagnostics.cacheTrace.filePath": "Cache Trace File Path",
  "diagnostics.cacheTrace.includeMessages": "Cache Trace Include Messages",
  "diagnostics.cacheTrace.includePrompt": "Cache Trace Include Prompt",
  "diagnostics.cacheTrace.includeSystem": "Cache Trace Include System",
  "agents.list.*.identity.avatar": "Identity Avatar",
  "agents.list.*.skills": "Agent Skill Filter",
  "gateway.remote.url": "Remote Gateway URL",
  "gateway.remote.sshTarget": "Remote Gateway SSH Target",
  "gateway.remote.sshIdentity": "Remote Gateway SSH Identity",
  "gateway.remote.token": "Remote Gateway Token",
  "gateway.remote.password": "Remote Gateway Password",
  "gateway.remote.tlsFingerprint": "Remote Gateway TLS Fingerprint",
  "gateway.auth.token": "Gateway Token",
  "gateway.auth.password": "Gateway Password",
  "tools.media.image.enabled": "Enable Image Understanding",
  "tools.media.image.maxBytes": "Image Understanding Max Bytes",
  "tools.media.image.maxChars": "Image Understanding Max Chars",
  "tools.media.image.prompt": "Image Understanding Prompt",
  "tools.media.image.timeoutSeconds": "Image Understanding Timeout (sec)",
  "tools.media.image.attachments": "Image Understanding Attachment Policy",
  "tools.media.image.models": "Image Understanding Models",
  "tools.media.image.scope": "Image Understanding Scope",
  "tools.media.models": "Media Understanding Shared Models",
  "tools.media.concurrency": "Media Understanding Concurrency",
  "tools.media.audio.enabled": "Enable Audio Understanding",
  "tools.media.audio.maxBytes": "Audio Understanding Max Bytes",
  "tools.media.audio.maxChars": "Audio Understanding Max Chars",
  "tools.media.audio.prompt": "Audio Understanding Prompt",
  "tools.media.audio.timeoutSeconds": "Audio Understanding Timeout (sec)",
  "tools.media.audio.language": "Audio Understanding Language",
  "tools.media.audio.attachments": "Audio Understanding Attachment Policy",
  "tools.media.audio.models": "Audio Understanding Models",
  "tools.media.audio.scope": "Audio Understanding Scope",
  "tools.media.video.enabled": "Enable Video Understanding",
  "tools.media.video.maxBytes": "Video Understanding Max Bytes",
  "tools.media.video.maxChars": "Video Understanding Max Chars",
  "tools.media.video.prompt": "Video Understanding Prompt",
  "tools.media.video.timeoutSeconds": "Video Understanding Timeout (sec)",
  "tools.media.video.attachments": "Video Understanding Attachment Policy",
  "tools.media.video.models": "Video Understanding Models",
  "tools.media.video.scope": "Video Understanding Scope",
  "tools.links.enabled": "Enable Link Understanding",
  "tools.links.maxLinks": "Link Understanding Max Links",
  "tools.links.timeoutSeconds": "Link Understanding Timeout (sec)",
  "tools.links.models": "Link Understanding Models",
  "tools.links.scope": "Link Understanding Scope",
  "tools.profile": "Tool Profile",
  "tools.alsoAllow": "Tool Allowlist Additions",
  "agents.list[].tools.profile": "Agent Tool Profile",
  "agents.list[].tools.alsoAllow": "Agent Tool Allowlist Additions",
  "tools.byProvider": "Tool Policy by Provider",
  "agents.list[].tools.byProvider": "Agent Tool Policy by Provider",
  "tools.exec.applyPatch.enabled": "Enable apply_patch",
  "tools.exec.applyPatch.workspaceOnly": "apply_patch Workspace-Only",
  "tools.exec.applyPatch.allowModels": "apply_patch Model Allowlist",
  "tools.fs.workspaceOnly": "Workspace-only FS tools",
  "tools.sessions.visibility": "Session Tools Visibility",
  "tools.exec.notifyOnExit": "Exec Notify On Exit",
  "tools.exec.notifyOnExitEmptySuccess": "Exec Notify On Empty Success",
  "tools.exec.approvalRunningNoticeMs": "Exec Approval Running Notice (ms)",
  "tools.exec.host": "Exec Host",
  "tools.exec.security": "Exec Security",
  "tools.exec.ask": "Exec Ask",
  "tools.exec.node": "Exec Node Binding",
  "tools.exec.pathPrepend": "Exec PATH Prepend",
  "tools.exec.safeBins": "Exec Safe Bins",
  "tools.message.allowCrossContextSend": "Allow Cross-Context Messaging",
  "tools.message.crossContext.allowWithinProvider": "Allow Cross-Context (Same Provider)",
  "tools.message.crossContext.allowAcrossProviders": "Allow Cross-Context (Across Providers)",
  "tools.message.crossContext.marker.enabled": "Cross-Context Marker",
  "tools.message.crossContext.marker.prefix": "Cross-Context Marker Prefix",
  "tools.message.crossContext.marker.suffix": "Cross-Context Marker Suffix",
  "tools.message.broadcast.enabled": "Enable Message Broadcast",
  "tools.web.search.enabled": "Enable Web Search Tool",
  "tools.web.search.provider": "Web Search Provider",
  "tools.web.search.apiKey": "Brave Search API Key",
  "tools.web.search.maxResults": "Web Search Max Results",
  "tools.web.search.timeoutSeconds": "Web Search Timeout (sec)",
  "tools.web.search.cacheTtlMinutes": "Web Search Cache TTL (min)",
  "tools.web.fetch.enabled": "Enable Web Fetch Tool",
  "tools.web.fetch.maxChars": "Web Fetch Max Chars",
  "tools.web.fetch.timeoutSeconds": "Web Fetch Timeout (sec)",
  "tools.web.fetch.cacheTtlMinutes": "Web Fetch Cache TTL (min)",
  "tools.web.fetch.maxRedirects": "Web Fetch Max Redirects",
  "tools.web.fetch.userAgent": "Web Fetch User-Agent",
  "gateway.controlUi.basePath": "Control UI Base Path",
  "gateway.controlUi.root": "Control UI Assets Root",
  "gateway.controlUi.allowedOrigins": "Control UI Allowed Origins",
  "gateway.controlUi.allowInsecureAuth": "Allow Insecure Control UI Auth",
  "gateway.http.endpoints.chatCompletions.enabled": "OpenAI Chat Completions Endpoint",
  "gateway.reload.mode": "Config Reload Mode",
  "gateway.reload.debounceMs": "Config Reload Debounce (ms)",
  "gateway.nodes.browser.mode": "Gateway Node Browser Mode",
  "gateway.nodes.browser.node": "Gateway Node Browser Pin",
  "gateway.nodes.allowCommands": "Gateway Node Allowlist (Extra Commands)",
  "gateway.nodes.denyCommands": "Gateway Node Denylist",
  "nodeHost.browserProxy.enabled": "Node Browser Proxy Enabled",
  "nodeHost.browserProxy.allowProfiles": "Node Browser Proxy Allowed Profiles",
  "skills.load.watch": "Watch Skills",
  "skills.load.watchDebounceMs": "Skills Watch Debounce (ms)",
  "agents.defaults.workspace": "Workspace",
  "agents.defaults.repoRoot": "Repo Root",
  "agents.defaults.bootstrapMaxChars": "Bootstrap Max Chars",
  "agents.defaults.bootstrapTotalMaxChars": "Bootstrap Total Max Chars",
  "agents.defaults.envelopeTimezone": "Envelope Timezone",
  "agents.defaults.envelopeTimestamp": "Envelope Timestamp",
  "agents.defaults.envelopeElapsed": "Envelope Elapsed",
  "agents.defaults.memorySearch": "Memory Search",
  "agents.defaults.memorySearch.enabled": "Enable Memory Search",
  "agents.defaults.memorySearch.sources": "Memory Search Sources",
  "agents.defaults.memorySearch.extraPaths": "Extra Memory Paths",
  "agents.defaults.memorySearch.experimental.sessionMemory":
    "Memory Search Session Index (Experimental)",
  "agents.defaults.memorySearch.provider": "Memory Search Provider",
  "agents.defaults.memorySearch.remote.baseUrl": "Remote Embedding Base URL",
  "agents.defaults.memorySearch.remote.apiKey": "Remote Embedding API Key",
  "agents.defaults.memorySearch.remote.headers": "Remote Embedding Headers",
  "agents.defaults.memorySearch.remote.batch.concurrency": "Remote Batch Concurrency",
  "agents.defaults.memorySearch.model": "Memory Search Model",
  "agents.defaults.memorySearch.fallback": "Memory Search Fallback",
  "agents.defaults.memorySearch.local.modelPath": "Local Embedding Model Path",
  "agents.defaults.memorySearch.store.path": "Memory Search Index Path",
  "agents.defaults.memorySearch.store.vector.enabled": "Memory Search Vector Index",
  "agents.defaults.memorySearch.store.vector.extensionPath": "Memory Search Vector Extension Path",
  "agents.defaults.memorySearch.chunking.tokens": "Memory Chunk Tokens",
  "agents.defaults.memorySearch.chunking.overlap": "Memory Chunk Overlap Tokens",
  "agents.defaults.memorySearch.sync.onSessionStart": "Index on Session Start",
  "agents.defaults.memorySearch.sync.onSearch": "Index on Search (Lazy)",
  "agents.defaults.memorySearch.sync.watch": "Watch Memory Files",
  "agents.defaults.memorySearch.sync.watchDebounceMs": "Memory Watch Debounce (ms)",
  "agents.defaults.memorySearch.sync.sessions.deltaBytes": "Session Delta Bytes",
  "agents.defaults.memorySearch.sync.sessions.deltaMessages": "Session Delta Messages",
  "agents.defaults.memorySearch.query.maxResults": "Memory Search Max Results",
  "agents.defaults.memorySearch.query.minScore": "Memory Search Min Score",
  "agents.defaults.memorySearch.query.hybrid.enabled": "Memory Search Hybrid",
  "agents.defaults.memorySearch.query.hybrid.vectorWeight": "Memory Search Vector Weight",
  "agents.defaults.memorySearch.query.hybrid.textWeight": "Memory Search Text Weight",
  "agents.defaults.memorySearch.query.hybrid.candidateMultiplier":
    "Memory Search Hybrid Candidate Multiplier",
  "agents.defaults.memorySearch.cache.enabled": "Memory Search Embedding Cache",
  "agents.defaults.memorySearch.cache.maxEntries": "Memory Search Embedding Cache Max Entries",
  memory: "Memory",
  "memory.backend": "Memory Backend",
  "memory.citations": "Memory Citations Mode",
  "memory.qmd.command": "QMD Binary",
  "memory.qmd.includeDefaultMemory": "QMD Include Default Memory",
  "memory.qmd.paths": "QMD Extra Paths",
  "memory.qmd.paths.path": "QMD Path",
  "memory.qmd.paths.pattern": "QMD Path Pattern",
  "memory.qmd.paths.name": "QMD Path Name",
  "memory.qmd.sessions.enabled": "QMD Session Indexing",
  "memory.qmd.sessions.exportDir": "QMD Session Export Directory",
  "memory.qmd.sessions.retentionDays": "QMD Session Retention (days)",
  "memory.qmd.update.interval": "QMD Update Interval",
  "memory.qmd.update.debounceMs": "QMD Update Debounce (ms)",
  "memory.qmd.update.onBoot": "QMD Update on Startup",
  "memory.qmd.update.waitForBootSync": "QMD Wait for Boot Sync",
  "memory.qmd.update.embedInterval": "QMD Embed Interval",
  "memory.qmd.update.commandTimeoutMs": "QMD Command Timeout (ms)",
  "memory.qmd.update.updateTimeoutMs": "QMD Update Timeout (ms)",
  "memory.qmd.update.embedTimeoutMs": "QMD Embed Timeout (ms)",
  "memory.qmd.limits.maxResults": "QMD Max Results",
  "memory.qmd.limits.maxSnippetChars": "QMD Max Snippet Chars",
  "memory.qmd.limits.maxInjectedChars": "QMD Max Injected Chars",
  "memory.qmd.limits.timeoutMs": "QMD Search Timeout (ms)",
  "memory.qmd.scope": "QMD Surface Scope",
  "auth.profiles": "Auth Profiles",
  "auth.order": "Auth Profile Order",
  "auth.cooldowns.billingBackoffHours": "Billing Backoff (hours)",
  "auth.cooldowns.billingBackoffHoursByProvider": "Billing Backoff Overrides",
  "auth.cooldowns.billingMaxHours": "Billing Backoff Cap (hours)",
  "auth.cooldowns.failureWindowHours": "Failover Window (hours)",
  "agents.defaults.models": "Models",
  "agents.defaults.model.primary": "Primary Model",
  "agents.defaults.model.fallbacks": "Model Fallbacks",
  "agents.defaults.imageModel.primary": "Image Model",
  "agents.defaults.imageModel.fallbacks": "Image Model Fallbacks",
  "agents.defaults.humanDelay.mode": "Human Delay Mode",
  "agents.defaults.humanDelay.minMs": "Human Delay Min (ms)",
  "agents.defaults.humanDelay.maxMs": "Human Delay Max (ms)",
  "agents.defaults.cliBackends": "CLI Backends",
  "commands.native": "Native Commands",
  "commands.nativeSkills": "Native Skill Commands",
  "commands.text": "Text Commands",
  "commands.bash": "Allow Bash Chat Command",
  "commands.bashForegroundMs": "Bash Foreground Window (ms)",
  "commands.config": "Allow /config",
  "commands.debug": "Allow /debug",
  "commands.restart": "Allow Restart",
  "commands.useAccessGroups": "Use Access Groups",
  "commands.ownerAllowFrom": "Command Owners",
  "ui.seamColor": "Accent Color",
  "ui.assistant.name": "Assistant Name",
  "ui.assistant.avatar": "Assistant Avatar",
  "browser.evaluateEnabled": "Browser Evaluate Enabled",
  "browser.snapshotDefaults": "Browser Snapshot Defaults",
  "browser.snapshotDefaults.mode": "Browser Snapshot Mode",
  "browser.remoteCdpTimeoutMs": "Remote CDP Timeout (ms)",
  "browser.remoteCdpHandshakeTimeoutMs": "Remote CDP Handshake Timeout (ms)",
  "session.dmScope": "DM Session Scope",
  "session.agentToAgent.maxPingPongTurns": "Agent-to-Agent Ping-Pong Turns",
  "messages.suppressToolErrors": "Suppress Tool Error Warnings",
  "messages.ackReaction": "Ack Reaction Emoji",
  "messages.ackReactionScope": "Ack Reaction Scope",
  "messages.inbound.debounceMs": "Inbound Message Debounce (ms)",
  "talk.apiKey": "Talk API Key",
  "channels.whatsapp": "WhatsApp",
  "channels.telegram": "Telegram",
  "channels.telegram.customCommands": "Telegram Custom Commands",
  "channels.discord": "Discord",
  "channels.slack": "Slack",
  "channels.mattermost": "Mattermost",
  "channels.signal": "Signal",
  "channels.imessage": "iMessage",
  "channels.bluebubbles": "BlueBubbles",
  "channels.msteams": "MS Teams",
  // ── Root section labels ────────────────────────────────────────────────
  meta: "Metadata",
  env: "Environment",
  wizard: "Setup Wizard",
  diagnostics: "Diagnostics",
  logging: "Logging",
  update: "Update",
  browser: "Browser",
  ui: "UI",
  auth: "Authentication",
  models: "Models",
  nodeHost: "Node Host",
  agents: "Agents",
  tools: "Tools",
  bindings: "Bindings",
  broadcast: "Broadcast",
  audio: "Audio",
  media: "Media",
  messages: "Messages",
  commands: "Commands",
  approvals: "Approvals",
  session: "Session",
  cron: "Cron",
  hooks: "Hooks",
  web: "Web",
  channels: "Channels",
  discovery: "Discovery",
  canvasHost: "Canvas Host",
  talk: "Talk",
  gateway: "Gateway",
  plugins: "Plugins",

  // ── TARGET_KEYS labels ────────────────────────────────────────────────
  "memory.qmd.searchMode": "QMD Search Mode",
  "memory.qmd.mcporter": "QMD MCP Transport",
  "memory.qmd.mcporter.enabled": "QMD MCP Enabled",
  "memory.qmd.mcporter.serverName": "QMD MCP Server Name",
  "memory.qmd.mcporter.startDaemon": "QMD MCP Start Daemon",
  "models.mode": "Model Merge Mode",
  "models.providers.*.auth": "Provider Auth Method",
  "models.providers.*.authHeader": "Provider Auth Header",
  "gateway.controlUi.dangerouslyAllowHostHeaderOriginFallback": "Allow Host Header Origin Fallback",
  "gateway.controlUi.dangerouslyDisableDeviceAuth": "Disable Device Auth",
  cron: "Cron",
  "cron.enabled": "Cron Enabled",
  "cron.store": "Cron Store",
  "cron.maxConcurrentRuns": "Cron Max Concurrent Runs",
  "cron.webhook": "Cron Webhook (Deprecated)",
  "cron.webhookToken": "Cron Webhook Token",
  "cron.sessionRetention": "Cron Session Retention",
  "cron.runLog": "Cron Run Log",
  "cron.runLog.maxBytes": "Cron Run Log Max Bytes",
  "cron.runLog.keepLines": "Cron Run Log Keep Lines",
  session: "Session",
  "session.scope": "Session Scope",
  "session.identityLinks": "Session Identity Links",
  "session.resetTriggers": "Session Reset Triggers",
  "session.idleMinutes": "Session Idle Minutes",
  "session.reset": "Session Reset",
  "session.reset.mode": "Session Reset Mode",
  "session.reset.atHour": "Session Reset Hour",
  "session.reset.idleMinutes": "Session Reset Idle Minutes",
  "session.resetByType": "Session Reset by Type",
  "session.resetByType.direct": "Session Reset (Direct)",
  "session.resetByType.dm": "Session Reset (DM)",
  "session.resetByType.group": "Session Reset (Group)",
  "session.resetByType.thread": "Session Reset (Thread)",
  "session.resetByChannel": "Session Reset by Channel",
  "session.store": "Session Store",
  "session.typingIntervalSeconds": "Typing Indicator Interval (sec)",
  "session.typingMode": "Typing Mode",
  "session.mainKey": "Session Main Key",
  "session.sendPolicy": "Send Policy",
  "session.sendPolicy.default": "Send Policy Default",
  "session.sendPolicy.rules": "Send Policy Rules",
  "session.sendPolicy.rules[].action": "Send Policy Rule Action",
  "session.sendPolicy.rules[].match": "Send Policy Rule Match",
  "session.sendPolicy.rules[].match.channel": "Send Policy Match Channel",
  "session.sendPolicy.rules[].match.chatType": "Send Policy Match Chat Type",
  "session.sendPolicy.rules[].match.keyPrefix": "Send Policy Match Key Prefix",
  "session.sendPolicy.rules[].match.rawKeyPrefix": "Send Policy Match Raw Key Prefix",
  "session.agentToAgent": "Agent-to-Agent",
  "session.threadBindings": "Thread Bindings",
  "session.threadBindings.enabled": "Thread Bindings Enabled",
  "session.threadBindings.ttlHours": "Thread Bindings TTL (hours)",
  "session.maintenance": "Session Maintenance",
  "session.maintenance.mode": "Maintenance Mode",
  "session.maintenance.pruneAfter": "Prune After",
  "session.maintenance.pruneDays": "Prune Days (Deprecated)",
  "session.maintenance.maxEntries": "Max Session Entries",
  "session.maintenance.rotateBytes": "Rotate Bytes",
  "session.maintenance.resetArchiveRetention": "Reset Archive Retention",
  "session.maintenance.maxDiskBytes": "Max Disk Bytes",
  "session.maintenance.highWaterBytes": "High Water Bytes",
  approvals: "Approvals",
  "approvals.exec": "Exec Approvals",
  "approvals.exec.enabled": "Exec Approvals Enabled",
  "approvals.exec.mode": "Exec Approvals Mode",
  "approvals.exec.agentFilter": "Exec Approvals Agent Filter",
  "approvals.exec.sessionFilter": "Exec Approvals Session Filter",
  "approvals.exec.targets": "Exec Approvals Targets",
  "approvals.exec.targets[].channel": "Approval Target Channel",
  "approvals.exec.targets[].to": "Approval Target Recipient",
  "approvals.exec.targets[].accountId": "Approval Target Account",
  "approvals.exec.targets[].threadId": "Approval Target Thread",
  nodeHost: "Node Host",
  "nodeHost.browserProxy": "Node Browser Proxy",
  media: "Media",
  "media.preserveFilenames": "Preserve Media Filenames",
  audio: "Audio",
  "audio.transcription": "Audio Transcription",
  "audio.transcription.command": "Transcription Command",
  "audio.transcription.timeoutSeconds": "Transcription Timeout (sec)",
  bindings: "Bindings",
  "bindings[].agentId": "Binding Agent ID",
  "bindings[].match": "Binding Match",
  "bindings[].match.channel": "Binding Match Channel",
  "bindings[].match.accountId": "Binding Match Account",
  "bindings[].match.peer": "Binding Match Peer",
  "bindings[].match.peer.kind": "Binding Peer Kind",
  "bindings[].match.peer.id": "Binding Peer ID",
  "bindings[].match.guildId": "Binding Guild ID",
  "bindings[].match.teamId": "Binding Team ID",
  "bindings[].match.roles": "Binding Roles",
  broadcast: "Broadcast",
  "broadcast.strategy": "Broadcast Strategy",
  "broadcast.*": "Broadcast Relay Map",
  commands: "Commands",
  "commands.allowFrom": "Command Allowlist",
  hooks: "Hooks",
  "hooks.enabled": "Hooks Enabled",
  "hooks.path": "Hooks Path",
  "hooks.token": "Hooks Token",
  "hooks.defaultSessionKey": "Hooks Default Session Key",
  "hooks.allowRequestSessionKey": "Hooks Allow Request Session Key",
  "hooks.allowedSessionKeyPrefixes": "Hooks Allowed Key Prefixes",
  "hooks.allowedAgentIds": "Hooks Allowed Agent IDs",
  "hooks.maxBodyBytes": "Hooks Max Body Bytes",
  "hooks.transformsDir": "Hooks Transforms Directory",
  "hooks.mappings": "Hooks Mappings",
  "hooks.mappings[].action": "Hook Mapping Action",
  "hooks.mappings[].wakeMode": "Hook Mapping Wake Mode",
  "hooks.mappings[].channel": "Hook Mapping Channel",
  "hooks.mappings[].transform.module": "Hook Transform Module",
  "hooks.gmail": "Gmail Hooks",
  "hooks.gmail.pushToken": "Gmail Push Token",
  "hooks.gmail.tailscale.mode": "Gmail Tailscale Mode",
  "hooks.gmail.thinking": "Gmail Thinking Depth",
  "hooks.internal": "Internal Hooks",
  "hooks.internal.handlers": "Internal Handlers",
  "hooks.internal.handlers[].event": "Internal Handler Event",
  "hooks.internal.handlers[].module": "Internal Handler Module",
  "hooks.internal.load.extraDirs": "Internal Handlers Extra Dirs",
  messages: "Messages",
  "messages.messagePrefix": "Message Prefix",
  "messages.responsePrefix": "Response Prefix",
  "messages.groupChat": "Group Chat",
  "messages.groupChat.mentionPatterns": "Group Chat Mention Patterns",
  "messages.groupChat.historyLimit": "Group Chat History Limit",
  "messages.queue": "Message Queue",
  "messages.queue.mode": "Queue Mode",
  "messages.queue.byChannel": "Queue Mode by Channel",
  "messages.queue.debounceMs": "Queue Debounce (ms)",
  "messages.queue.debounceMsByChannel": "Queue Debounce by Channel",
  "messages.queue.cap": "Queue Cap",
  "messages.queue.drop": "Queue Overflow Strategy",
  "messages.inbound": "Inbound Messages",
  "messages.inbound.byChannel": "Inbound by Channel",
  "messages.removeAckAfterReply": "Remove Ack After Reply",
  "messages.tts": "Message TTS",
  "channels.defaults": "Channel Defaults",
  "channels.defaults.groupPolicy": "Default Group Policy",
  "channels.defaults.heartbeat": "Default Heartbeat",
  "channels.defaults.heartbeat.showOk": "Heartbeat Show OK",
  "channels.defaults.heartbeat.showAlerts": "Heartbeat Show Alerts",
  "channels.defaults.heartbeat.useIndicator": "Heartbeat Use Indicator",
  gateway: "Gateway",
  "gateway.mode": "Gateway Mode",
  "gateway.bind": "Gateway Bind",
  "gateway.auth.mode": "Gateway Auth Mode",
  "gateway.tailscale.mode": "Gateway Tailscale Mode",
  "gateway.tools.allow": "Gateway Tool Allowlist",
  "gateway.tools.deny": "Gateway Tool Denylist",
  "gateway.tls.enabled": "Gateway TLS Enabled",
  "gateway.tls.autoGenerate": "Gateway TLS Auto-Generate",
  "gateway.http": "Gateway HTTP",
  "gateway.http.endpoints": "Gateway HTTP Endpoints",
  browser: "Browser",
  "browser.enabled": "Browser Enabled",
  "browser.cdpUrl": "Browser CDP URL",
  "browser.headless": "Browser Headless",
  "browser.noSandbox": "Browser No Sandbox",
  "browser.profiles": "Browser Profiles",
  "browser.profiles.*.driver": "Browser Profile Driver",
  tools: "Tools",
  "tools.allow": "Tool Allowlist",
  "tools.deny": "Tool Denylist",
  "tools.exec": "Tool Exec",
  "tools.agentToAgent.enabled": "Agent-to-Agent Tools Enabled",
  "tools.elevated.enabled": "Elevated Tools Enabled",
  "tools.elevated.allowFrom": "Elevated Tools Allowlist",
  "tools.subagents.tools": "Subagent Tools",
  "tools.sandbox.tools": "Sandbox Tools",
  web: "Web",
  "web.enabled": "Web UI Enabled",
  "web.heartbeatSeconds": "Web Heartbeat (sec)",
  "web.reconnect": "Web Reconnect",
  "web.reconnect.initialMs": "Web Reconnect Initial (ms)",
  "web.reconnect.maxMs": "Web Reconnect Max (ms)",
  "web.reconnect.factor": "Web Reconnect Factor",
  "web.reconnect.jitter": "Web Reconnect Jitter",
  "web.reconnect.maxAttempts": "Web Reconnect Max Attempts",
  discovery: "Discovery",
  "discovery.wideArea.enabled": "Wide-Area Discovery Enabled",
  "discovery.mdns": "mDNS Discovery",
  canvasHost: "Canvas Host",
  "canvasHost.enabled": "Canvas Host Enabled",
  "canvasHost.root": "Canvas Host Root",
  "canvasHost.port": "Canvas Host Port",
  "canvasHost.liveReload": "Canvas Host Live Reload",
  talk: "Talk",
  "talk.voiceId": "Talk Voice ID",
  "talk.voiceAliases": "Talk Voice Aliases",
  "talk.modelId": "Talk Model ID",
  "talk.outputFormat": "Talk Output Format",
  "talk.interruptOnSpeech": "Talk Interrupt on Speech",
  "env.shellEnv": "Shell Environment",
  "env.shellEnv.enabled": "Shell Environment Enabled",
  "env.shellEnv.timeoutMs": "Shell Environment Timeout (ms)",
  "env.vars": "Environment Variables",
  "wizard.lastRunAt": "Wizard Last Run At",
  "wizard.lastRunVersion": "Wizard Last Run Version",
  "wizard.lastRunCommit": "Wizard Last Run Commit",
  "wizard.lastRunCommand": "Wizard Last Run Command",
  "wizard.lastRunMode": "Wizard Last Run Mode",
  "diagnostics.otel": "OpenTelemetry",
  "logging.level": "Log Level",
  "logging.file": "Log File",
  "logging.consoleLevel": "Console Log Level",
  "logging.consoleStyle": "Console Log Style",
  "logging.redactSensitive": "Redact Sensitive Data",
  "logging.redactPatterns": "Redact Patterns",
  "ui.assistant": "Assistant",
  "plugins.entries.*.apiKey": "Plugin API Key",
  "plugins.entries.*.env": "Plugin Environment",
  "auth.cooldowns": "Auth Cooldowns",
  "models.providers": "Model Providers",
  "models.providers.*.baseUrl": "Provider Base URL",
  "models.providers.*.apiKey": "Provider API Key",
  "models.providers.*.api": "Provider API Format",
  "models.providers.*.headers": "Provider Headers",
  "models.providers.*.models": "Provider Models",
  "models.bedrockDiscovery": "Bedrock Discovery",
  "models.bedrockDiscovery.enabled": "Bedrock Discovery Enabled",
  "models.bedrockDiscovery.region": "Bedrock Discovery Region",
  "models.bedrockDiscovery.providerFilter": "Bedrock Provider Filter",
  "models.bedrockDiscovery.refreshInterval": "Bedrock Refresh Interval",
  "models.bedrockDiscovery.defaultContextWindow": "Bedrock Default Context Window",
  "models.bedrockDiscovery.defaultMaxTokens": "Bedrock Default Max Tokens",
  "agents.defaults": "Agent Defaults",
  "agents.list": "Agent List",
  "agents.defaults.compaction": "Compaction",
  "agents.defaults.compaction.mode": "Compaction Mode",
  "agents.defaults.compaction.reserveTokens": "Compaction Reserve Tokens",
  "agents.defaults.compaction.keepRecentTokens": "Compaction Keep Recent Tokens",
  "agents.defaults.compaction.reserveTokensFloor": "Compaction Reserve Floor",
  "agents.defaults.compaction.maxHistoryShare": "Compaction Max History Share",
  "agents.defaults.compaction.memoryFlush": "Memory Flush",
  "agents.defaults.compaction.memoryFlush.enabled": "Memory Flush Enabled",
  "agents.defaults.compaction.memoryFlush.softThresholdTokens": "Memory Flush Soft Threshold",
  "agents.defaults.compaction.memoryFlush.prompt": "Memory Flush Prompt",
  "agents.defaults.compaction.memoryFlush.systemPrompt": "Memory Flush System Prompt",

  // ── TOOLS_HOOKS_TARGET_KEYS labels ────────────────────────────────────
  "hooks.gmail.account": "Gmail Account",
  "hooks.gmail.allowUnsafeExternalContent": "Gmail Allow Unsafe Content",
  "hooks.gmail.hookUrl": "Gmail Hook URL",
  "hooks.gmail.includeBody": "Gmail Include Body",
  "hooks.gmail.label": "Gmail Label",
  "hooks.gmail.model": "Gmail Model",
  "hooks.gmail.serve": "Gmail Serve",
  "hooks.gmail.subscription": "Gmail Subscription",
  "hooks.gmail.tailscale": "Gmail Tailscale",
  "hooks.gmail.topic": "Gmail Topic",
  "hooks.internal.entries": "Internal Entries",
  "hooks.internal.installs": "Internal Installs",
  "hooks.internal.load": "Internal Load",
  "hooks.mappings[].allowUnsafeExternalContent": "Hook Allow Unsafe Content",
  "hooks.mappings[].deliver": "Hook Deliver",
  "hooks.mappings[].id": "Hook Mapping ID",
  "hooks.mappings[].match": "Hook Match",
  "hooks.mappings[].messageTemplate": "Hook Message Template",
  "hooks.mappings[].model": "Hook Model",
  "hooks.mappings[].name": "Hook Mapping Name",
  "hooks.mappings[].textTemplate": "Hook Text Template",
  "hooks.mappings[].thinking": "Hook Thinking Depth",
  "hooks.mappings[].transform": "Hook Transform",

  // ── CHANNELS_AGENTS_TARGET_KEYS labels ────────────────────────────────
  "agents.defaults.memorySearch.query.hybrid.mmr.enabled": "Memory Search MMR Enabled",
  "agents.defaults.memorySearch.query.hybrid.mmr.lambda": "Memory Search MMR Lambda",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.enabled": "Memory Search Temporal Decay",
  "agents.defaults.memorySearch.query.hybrid.temporalDecay.halfLifeDays":
    "Memory Search Temporal Half-Life",
  "channels.irc": "IRC",
  "channels.telegram.capabilities.inlineButtons": "Telegram Inline Buttons",

  // ── FINAL_BACKLOG_TARGET_KEYS labels ──────────────────────────────────
  "browser.ssrfPolicy": "Browser SSRF Policy",
  "browser.ssrfPolicy.allowPrivateNetwork": "SSRF Allow Private Network",
  "browser.ssrfPolicy.dangerouslyAllowPrivateNetwork": "SSRF Dangerously Allow Private Network",
  "browser.ssrfPolicy.allowedHostnames": "SSRF Allowed Hostnames",
  "browser.ssrfPolicy.hostnameAllowlist": "SSRF Hostname Allowlist",

  // ── FIELD_HELP-only keys that need labels ─────────────────────────────
  "agents.defaults.heartbeat.suppressToolErrorWarnings": "Suppress Heartbeat Tool Errors",
  "agents.list[].heartbeat.suppressToolErrorWarnings": "Agent Suppress Heartbeat Tool Errors",
  "diagnostics.cacheTrace": "Cache Trace",
  "tools.web.search.perplexity.apiKey": "Perplexity API Key",
  "tools.web.search.perplexity.baseUrl": "Perplexity Base URL",
  "tools.web.search.perplexity.model": "Perplexity Model",
  "tools.web.urlAllowlist": "Web URL Allowlist",
  "tools.web.fetch.maxCharsCap": "Web Fetch Max Chars Cap",
  "tools.web.fetch.readability": "Web Fetch Readability",
  "tools.web.fetch.firecrawl.enabled": "Firecrawl Enabled",
  "tools.web.fetch.firecrawl.apiKey": "Firecrawl API Key",
  "tools.web.fetch.firecrawl.baseUrl": "Firecrawl Base URL",
  "tools.web.fetch.firecrawl.onlyMainContent": "Firecrawl Only Main Content",
  "tools.web.fetch.firecrawl.maxAgeMs": "Firecrawl Max Age (ms)",
  "tools.web.fetch.firecrawl.timeoutSeconds": "Firecrawl Timeout (sec)",
  "channels.slack.allowBots": "Slack Allow Bot Messages",
  "channels.slack.thread.historyScope": "Slack Thread History Scope",
  "channels.slack.thread.inheritParent": "Slack Thread Parent Inheritance",
  "channels.slack.thread.initialHistoryLimit": "Slack Thread Initial History Limit",
  "channels.mattermost.botToken": "Mattermost Bot Token",
  "channels.mattermost.baseUrl": "Mattermost Base URL",
  "channels.mattermost.chatmode": "Mattermost Chat Mode",
  "channels.mattermost.oncharPrefixes": "Mattermost Onchar Prefixes",
  "channels.mattermost.requireMention": "Mattermost Require Mention",
  "agents.defaults.memorySearch.remote.batch.enabled": "Remote Batch Enabled",
  "agents.defaults.memorySearch.remote.batch.wait": "Remote Batch Wait",
  "agents.defaults.memorySearch.remote.batch.pollIntervalMs": "Remote Batch Poll Interval (ms)",
  "agents.defaults.memorySearch.remote.batch.timeoutMinutes": "Remote Batch Timeout (min)",
  "channels.telegram.configWrites": "Telegram Config Writes",
  "channels.slack.configWrites": "Slack Config Writes",
  "channels.mattermost.configWrites": "Mattermost Config Writes",
  "channels.discord.configWrites": "Discord Config Writes",
  "channels.discord.proxy": "Discord Proxy",
  "channels.whatsapp.configWrites": "WhatsApp Config Writes",
  "channels.signal.configWrites": "Signal Config Writes",
  "channels.imessage.configWrites": "iMessage Config Writes",
  "channels.msteams.configWrites": "MS Teams Config Writes",
  "channels.discord.commands.native": "Discord Native Commands",
  "channels.discord.commands.nativeSkills": "Discord Native Skill Commands",
  "channels.telegram.commands.native": "Telegram Native Commands",
  "channels.telegram.commands.nativeSkills": "Telegram Native Skill Commands",
  "channels.slack.commands.native": "Slack Native Commands",
  "channels.slack.commands.nativeSkills": "Slack Native Skill Commands",
  "channels.slack.streamMode": "Slack Stream Mode",
  "channels.telegram.dmPolicy": "Telegram DM Policy",
  "channels.telegram.streamMode": "Telegram Stream Mode",
  "channels.telegram.draftChunk.minChars": "Telegram Draft Chunk Min Chars",
  "channels.telegram.draftChunk.maxChars": "Telegram Draft Chunk Max Chars",
  "channels.telegram.draftChunk.breakPreference": "Telegram Draft Chunk Break Preference",
  "channels.telegram.retry.attempts": "Telegram Retry Attempts",
  "channels.telegram.retry.minDelayMs": "Telegram Retry Min Delay (ms)",
  "channels.telegram.retry.maxDelayMs": "Telegram Retry Max Delay (ms)",
  "channels.telegram.retry.jitter": "Telegram Retry Jitter",
  "channels.telegram.network.autoSelectFamily": "Telegram autoSelectFamily",
  "channels.telegram.timeoutSeconds": "Telegram API Timeout (seconds)",
  "channels.whatsapp.dmPolicy": "WhatsApp DM Policy",
  "channels.whatsapp.selfChatMode": "WhatsApp Self-Phone Mode",
  "channels.whatsapp.debounceMs": "WhatsApp Message Debounce (ms)",
  "channels.signal.dmPolicy": "Signal DM Policy",
  "channels.imessage.dmPolicy": "iMessage DM Policy",
  "channels.bluebubbles.dmPolicy": "BlueBubbles DM Policy",
  "channels.discord.dmPolicy": "Discord DM Policy",
  "channels.discord.dm.policy": "Discord DM Policy (Legacy)",
  "channels.discord.retry.attempts": "Discord Retry Attempts",
  "channels.discord.retry.minDelayMs": "Discord Retry Min Delay (ms)",
  "channels.discord.retry.maxDelayMs": "Discord Retry Max Delay (ms)",
  "channels.discord.retry.jitter": "Discord Retry Jitter",
  "channels.discord.maxLinesPerMessage": "Discord Max Lines Per Message",
  "channels.discord.ui.components.accentColor": "Discord Component Accent Color",
  "channels.discord.intents.presence": "Discord Presence Intent",
  "channels.discord.intents.guildMembers": "Discord Guild Members Intent",
  "channels.discord.pluralkit.enabled": "Discord PluralKit Enabled",
  "channels.discord.pluralkit.token": "Discord PluralKit Token",
  "channels.discord.activity": "Discord Presence Activity",
  "channels.discord.status": "Discord Presence Status",
  "channels.discord.activityType": "Discord Presence Activity Type",
  "channels.discord.activityUrl": "Discord Presence Activity URL",
  "channels.slack.dm.policy": "Slack DM Policy (Legacy)",
  "channels.slack.dmPolicy": "Slack DM Policy",
  "agents.list[].identity.avatar": "Agent Avatar",
  "agents.list[].skills": "Agent Skill Filter",
  "plugins.slots.memory": "Memory Plugin",
  "plugins.installs.*.source": "Plugin Install Source",
  "plugins.installs.*.spec": "Plugin Install Spec",
  "plugins.installs.*.sourcePath": "Plugin Install Source Path",
  "plugins.installs.*.installPath": "Plugin Install Path",
  "plugins.installs.*.version": "Plugin Install Version",
  "plugins.installs.*.installedAt": "Plugin Install Time",
  "channels.telegram.botToken": "Telegram Bot Token",
  "channels.discord.token": "Discord Bot Token",
  "channels.slack.botToken": "Slack Bot Token",
  "channels.slack.appToken": "Slack App Token",
  "channels.slack.userToken": "Slack User Token",
  "channels.slack.userTokenReadOnly": "Slack User Token Read Only",
  "channels.signal.account": "Signal Account",
  "channels.imessage.cliPath": "iMessage CLI Path",
  "discovery.mdns.mode": "mDNS Discovery Mode",
  "plugins.enabled": "Enable Plugins",
  "plugins.allow": "Plugin Allowlist",
  "plugins.deny": "Plugin Denylist",
  "plugins.load": "Plugin Load",
  "plugins.load.paths": "Plugin Load Paths",
  "plugins.slots": "Plugin Slots",
  "plugins.entries": "Plugin Entries",
  "plugins.entries.*.enabled": "Plugin Enabled",
  "plugins.entries.*.config": "Plugin Config",
  "plugins.installs": "Plugin Install Records",

  // --- messages labels ---
  "messages.greeting": "Greeting Message",
  "messages.systemPrompt": "System Prompt",
  "messages.ignorePattern": "Ignore Pattern",
  "messages.queue.maxWait": "Queue Max Wait (ms)",
  "messages.queue.debounce": "Queue Debounce (ms)",
  "messages.queue.collapsePeriod": "Queue Collapse Period (ms)",

  // --- channels.defaults labels ---
  "channels.defaults.dmPolicy": "Default DM Policy",
  "channels.defaults.allowFrom": "Default Allow From",
  "channels.defaults.groupAllowlist": "Default Group Allowlist",
  "channels.defaults.groupAllowlistPatterns": "Default Group Allowlist Patterns",
  "channels.defaults.groupAllowFrom": "Default Group Allow From",
  "channels.defaults.presence": "Default Presence",
  "channels.defaults.presence.statusLine": "Default Presence Status Line",
  "channels.defaults.presence.afkText": "Default Presence AFK Text",

  // --- gateway labels ---
  "gateway.port": "Gateway Port",
  "gateway.host": "Gateway Host",
  "gateway.url": "Gateway External URL",
  "gateway.auth": "Gateway Auth",
  "gateway.tailscale": "Gateway Tailscale",
  "gateway.tailscale.hostname": "Tailscale Hostname",
  "gateway.tailscale.timeout": "Tailscale Timeout",
  "gateway.tailscale.stateDir": "Tailscale State Directory",
  "gateway.reload": "Gateway Reload",
  "gateway.controlUi": "Control UI",
  "gateway.controlUi.enabled": "Control UI Enabled",

  // --- browser labels ---
  "browser.profiles.*.binaryPath": "Browser Binary Path",
  "browser.profiles.*.dataDir": "Browser Data Directory",
  "browser.profiles.*.contextMode": "Browser Context Mode",
  "browser.profiles.*.viewport": "Browser Viewport",

  // --- tools.web labels ---
  "tools.web.search.command": "Web Search Command",
  "tools.web.search.backend": "Web Search Backend",
  "tools.web.fetch.driver": "Web Fetch Driver",
  "tools.web.fetch.maxPages": "Web Fetch Max Pages",

  // --- web provider labels ---
  "web.port": "Web UI Port",
  "web.host": "Web UI Host",
  "web.auth": "Web UI Auth",
  "web.auth.token": "Web UI Auth Token",
  "web.auth.password": "Web UI Auth Password",

  // --- discovery labels ---
  "discovery.enabled": "Discovery Enabled",
  "discovery.mdns.instanceName": "mDNS Instance Name",

  // --- canvasHost labels ---
  "canvasHost.auth": "Canvas Auth",
  "canvasHost.auth.token": "Canvas Auth Token",

  // --- talk labels ---
  "talk.enabled": "Talk Enabled",
  "talk.model": "Talk Model",
};
