import type { PluginCompatRecord } from "./types.js";

const MARKING_DATE = "2026-07-25";
const DEFAULT_REMOVE_AFTER = "2026-10-01";

/** Dated metadata for shipped deprecated surfaces that previously had annotations only. */
export const DEPRECATION_MARKING_COMPAT_RECORDS = [
  {
    code: "plugin-sdk-channel-setup-input-fields",
    status: "deprecated",
    owner: "channel",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "plugin-local setup input intersections that declare each owning channel field",
    docsPath: "/plugins/sdk-migration#published-channel-setup-compatibility",
    surfaces: [
      "ChannelSetupInput.privateKey",
      "ChannelSetupInput.secret",
      "ChannelSetupInput.botToken",
      "ChannelSetupInput.appToken",
      "ChannelSetupInput.signingSecret",
      "ChannelSetupInput.mode",
      "ChannelSetupInput.cliPath",
      "ChannelSetupInput.authDir",
      "ChannelSetupInput.httpUrl",
      "ChannelSetupInput.httpPort",
      "ChannelSetupInput.webhookPath",
      "ChannelSetupInput.webhookUrl",
      "ChannelSetupInput.userId",
      "ChannelSetupInput.accessToken",
      "ChannelSetupInput.password",
      "ChannelSetupInput.deviceName",
      "ChannelSetupInput.url",
      "ChannelSetupInput.baseUrl",
      "ChannelSetupInput.code",
      "ChannelSetupInput.groupChannels",
      "ChannelSetupInput.dmAllowlist",
      "ChannelSetupInput.autoDiscoverChannels",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on the reader-backed ChannelSetupInput compatibility tier",
      "published-plugin artifact reader sweep required before field removal",
    ],
    tests: ["src/plugin-sdk/channel-setup.test.ts", "src/plugins/compat/registry.test.ts"],
    releaseNote:
      "ChannelSetupInput keeps its reader-backed channel fields through the dated migration window while plugins move them into plugin-local input types.",
  },
  {
    code: "plugin-sdk-broad-runtime-barrels",
    status: "deprecated",
    owner: "sdk",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "focused plugin SDK subpaths for each runtime capability",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "bot/plugin-sdk/agent-runtime",
      "bot/plugin-sdk/agent-runtime loadModelCatalog params.useCache",
      "bot/plugin-sdk/agent-runtime loadModelCatalog params.cacheOnly",
      "bot/plugin-sdk/agent-runtime loadModelCatalog params.metadataSnapshot",
      "bot/plugin-sdk/agent-runtime loadModelCatalog",
      "bot/plugin-sdk/cli-runtime",
      "bot/plugin-sdk/conversation-runtime",
      "bot/plugin-sdk/hook-runtime",
      "bot/plugin-sdk/media-runtime",
      "bot/plugin-sdk/media-runtime buildAgentMediaPayload",
      "bot/plugin-sdk/plugin-runtime",
      "bot/plugin-sdk/security-runtime",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on broad plugin SDK barrels",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/plugin-sdk-subpaths.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Broad agent, CLI, conversation, hook, media, plugin, and security runtime barrels remain available while bundled and external plugins migrate to focused subpaths.",
  },
  {
    code: "plugin-sdk-provider-owned-helper-shims",
    status: "deprecated",
    owner: "provider",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "provider-local auth, model, replay, OAuth, and stream helper APIs",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "bot/plugin-sdk/provider-stream GOOGLE_THINKING_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream KILOCODE_THINKING_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream MOONSHOT_THINKING_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream MINIMAX_FAST_MODE_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream OPENAI_RESPONSES_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream OPENROUTER_THINKING_STREAM_HOOKS",
      "bot/plugin-sdk/provider-stream TOOL_STREAM_DEFAULT_ON_HOOKS",
      "bot/plugin-sdk/provider-stream-shared defaultToolStreamExtraParams",
      "bot/plugin-sdk/provider-stream-shared stripTrailingAnthropicAssistantPrefillWhenThinking",
      "bot/plugin-sdk/provider-stream-shared createAnthropicThinkingPrefillPayloadWrapper",
      "bot/plugin-sdk/provider-stream-shared OpenAICompatibleThinkingLevel",
      "bot/plugin-sdk/provider-stream-shared isOpenAICompatibleThinkingEnabled",
      "bot/plugin-sdk/provider-stream-shared DeepSeekV4ThinkingLevel",
      "bot/plugin-sdk/provider-stream-shared DeepSeekV4ReasoningEffort",
      "bot/plugin-sdk/provider-stream-shared createDeepSeekV4OpenAICompatibleThinkingWrapper",
      "bot/plugin-sdk/provider-stream-shared createThinkingOnlyFinalTextWrapper",
      "bot/plugin-sdk/provider-stream-shared createGoogleThinkingPayloadWrapper",
      "bot/plugin-sdk/provider-stream-shared createGoogleThinkingStreamWrapper",
      "bot/plugin-sdk/provider-model-shared isProxyReasoningUnsupportedModelHint",
      "bot/plugin-sdk/provider-model-shared OPENAI_COMPATIBLE_REPLAY_HOOKS",
      "bot/plugin-sdk/provider-model-shared ANTHROPIC_BY_MODEL_REPLAY_HOOKS",
      "bot/plugin-sdk/provider-model-shared NATIVE_ANTHROPIC_REPLAY_HOOKS",
      "bot/plugin-sdk/provider-model-shared PASSTHROUGH_GEMINI_REPLAY_HOOKS",
      "bot/plugin-sdk/provider-auth DEFAULT_COPILOT_API_BASE_URL",
      "bot/plugin-sdk/provider-auth deriveCopilotApiBaseUrlFromToken",
      "bot/plugin-sdk/provider-auth resolveCopilotApiToken",
      "bot/plugin-sdk/provider-auth-login.runtime loginChutes",
      "bot/plugin-sdk/provider-auth-login.runtime loginOpenAICodexOAuth",
      "bot/plugin-sdk/provider-auth-login.runtime githubCopilotLoginCommand",
      "bot/plugin-sdk/provider-auth-copilot-cache CachedCopilotToken",
      "bot/plugin-sdk/github-copilot-login githubCopilotLoginCommand",
      "bot/plugin-sdk/oauth-utils toFormUrlEncoded",
      "bot/plugin-sdk/oauth-utils generatePkceVerifierChallenge",
      "bot/plugin-sdk/provider-oauth-runtime OAuthProvider",
      "bot/plugin-sdk/provider-oauth-runtime OAuthProviderInfo",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming provider-local replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/plugin-sdk-subpaths.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Provider-specific auth, model, replay, OAuth, and stream shortcuts remain as deprecated SDK shims while providers move to their local APIs.",
  },
  {
    code: "message-presentation-legacy-bridges",
    status: "deprecated",
    owner: "channel",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "MessagePresentation values and channel presentation renderers",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "InteractiveReplyButton.value",
      "InteractiveReplyButton.url",
      "InteractiveReplyButton.webApp",
      "InteractiveReplyButton.web_app",
      "InteractiveReplyOption.value",
      "InteractiveReplyButton",
      "InteractiveReplyOption",
      "InteractiveReplyBlock",
      "InteractiveReply",
      "normalizeInteractiveReply",
      "hasInteractiveReplyBlocks",
      "presentationToInteractiveReply",
      "presentationToInteractiveControlsReply",
      "interactiveReplyToPresentation",
      "resolveInteractiveTextFallback",
      "src/auto-reply ReplyPayload.interactive",
      "bot/plugin-sdk/reply-payload ReplyPayload.interactive",
      "reduceInteractiveReply",
      "@hanzo/bot-discord buildDiscordInteractiveComponents",
      "@hanzo/bot-slack buildSlackInteractiveBlocks",
      "@hanzo/bot-telegram buildTelegramInteractiveButtons",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming MessagePresentation replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/interactive/payload.test.ts",
      "src/plugin-sdk/reply-payload.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Legacy interactive reply values and channel-specific rendering bridges remain available while producers migrate to MessagePresentation.",
  },
  {
    code: "plugin-sdk-focused-compat-aliases",
    status: "deprecated",
    owner: "sdk",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "the focused replacement named by each TypeScript @deprecated annotation",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "bot/plugin-sdk/acp-runtime __testing",
      "bot/plugin-sdk/approval-reaction-runtime",
      "bot/plugin-sdk/channel-inbound BuildChannelTurnContextParams",
      "bot/plugin-sdk/channel-inbound BuiltChannelTurnContext",
      "bot/plugin-sdk/channel-inbound buildChannelTurnContext",
      "bot/plugin-sdk/channel-inbound finalizeChannelInboundContext",
      "bot/plugin-sdk/channel-inbound filterChannelTurnSupplementalContext",
      "bot/plugin-sdk/channel-send-result ChannelSendRawResult",
      "bot/plugin-sdk/command-auth",
      "bot/plugin-sdk/command-auth ResolveSenderCommandAuthorizationParams",
      "bot/plugin-sdk/command-auth resolveCommandAuthorizedFromAuthorizers",
      "bot/plugin-sdk/command-auth CommandAuthorizationRuntime",
      "bot/plugin-sdk/command-auth ResolveSenderCommandAuthorizationWithRuntimeParams",
      "bot/plugin-sdk/command-auth resolveDirectDmAuthorizationOutcome",
      "bot/plugin-sdk/command-auth resolveSenderCommandAuthorizationWithRuntime",
      "bot/plugin-sdk/command-auth resolveSenderCommandAuthorization",
      "bot/plugin-sdk/keyed-async-queue KeyedAsyncQueue.getTailMapForTesting",
      "bot/plugin-sdk/persistent-dedupe PersistentDedupeLegacyPathOptions.lockOptions",
      "bot/plugin-sdk/retry-runtime createTelegramRetryRunner",
      "bot/plugin-sdk/ssrf-policy SsrfPolicyOptions.allowPrivateNetwork",
      "bot/plugin-sdk/ssrf-policy ssrfPolicyFromAllowPrivateNetwork",
      "bot/plugin-sdk/tts-runtime TtsSynthesisStreamResult",
      "bot/plugin-sdk/tts-runtime TtsRuntimeFacade._test",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations naming focused replacements",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugin-sdk/channel-inbound.test.ts",
      "src/plugin-sdk/command-auth.test.ts",
      "src/plugin-sdk/ssrf-policy.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Focused SDK compatibility aliases remain available through a dated window while callers adopt their annotated replacements.",
  },
  {
    code: "agent-harness-terminal-result-aliases",
    status: "deprecated",
    owner: "agent-runtime",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement:
      "AgentHarnessAttemptResult.terminal and AgentHarnessDeliveryDefaults.visibleReplies",
    docsPath: "/plugins/sdk-agent-harness",
    surfaces: [
      "AgentHarnessAttemptResult.aborted",
      "AgentHarnessAttemptResult.externalAbort",
      "AgentHarnessAttemptResult.timedOut",
      "AgentHarnessAttemptResult.idleTimedOut",
      "AgentHarnessAttemptResult.timedOutDuringCompaction",
      "AgentHarnessAttemptResult.timedOutDuringToolExecution",
      "AgentHarnessAttemptResult.timedOutByRunBudget",
      "AgentHarnessAttemptResult.promptError",
      "AgentHarnessAttemptResult.promptErrorSource",
      "AgentHarnessDeliveryDefaults.sourceVisibleReplies",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on agent harness result and delivery defaults",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/agents/harness/settled-turn-finalization-result.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Agent harness result booleans and sourceVisibleReplies remain available while harnesses migrate to terminal outcomes and visibleReplies.",
  },
  {
    code: "official-plugin-export-aliases",
    status: "deprecated",
    owner: "channel",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement:
      "the canonical testing export, MessagePresentation renderers, and host-owned timeout/runtime behavior",
    docsPath: "/plugins/compatibility#current-compatibility-areas",
    surfaces: [
      "@hanzo/bot-google-meet __testing",
      "@hanzo/bot-discord buildDiscordInteractiveComponents",
      "@hanzo/bot-discord normalizeDiscordListenerTimeoutMs",
      "@hanzo/bot-discord normalizeDiscordInboundWorkerTimeoutMs",
      "@hanzo/bot-discord isAbortError",
      "@hanzo/bot-discord runDiscordTaskWithTimeout",
      "@hanzo/bot-slack buildSlackInteractiveBlocks",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on published official-plugin exports",
      "plugin boundary report compatibility inventory",
    ],
    // Owning discord/slack suites live under extensions/*/src; the core import
    // guardrail forbids that path shape in core string literals, so cite the
    // package-root and registry tests here.
    tests: ["extensions/google-meet/index.test.ts", "src/plugins/compat/registry.test.ts"],
    releaseNote:
      "Published Google Meet testing, channel presentation, and Discord timeout aliases remain available while consumers move to their canonical exports and host-owned behavior.",
  },
  {
    code: "memory-host-compatibility-aliases",
    status: "deprecated",
    owner: "sdk",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "canonical memory cache/FTS tables and getRuntimeConfig or caller-provided config",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "@hanzo/bot-memory-host-sdk ensureMemoryIndexSchema.embeddingCacheTable",
      "@hanzo/bot-memory-host-sdk ensureMemoryIndexSchema.ftsTable",
      "@hanzo/bot-memory-host-sdk/runtime-core loadConfig",
      "@hanzo/bot-memory-host-sdk/host/bot-runtime loadConfig",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on memory-host SDK compatibility fields",
      "plugin boundary report memory-host SDK summary",
    ],
    tests: [
      "packages/memory-host-sdk/src/host/memory-schema.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Memory-host cache-table overrides and runtime config reload aliases remain available while callers migrate to canonical tables and prepared config.",
  },
  {
    code: "plugin-runtime-api-compat-aliases",
    status: "deprecated",
    owner: "plugin-execution",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "the namespaced plugin API and focused runtime methods named per surface",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "BotPluginApi.registerSessionExtension",
      "BotPluginApi.enqueueNextTurnInjection",
      "BotPluginApi.registerControlUiDescriptor",
      "BotPluginApi.registerRuntimeLifecycle",
      "BotPluginApi.registerAgentEventSubscription",
      "BotPluginApi.emitAgentEvent",
      "BotPluginApi.setRunContext",
      "BotPluginApi.getRunContext",
      "BotPluginApi.clearRunContext",
      "BotPluginApi.registerSessionSchedulerJob",
      "BotPluginApi.registerSessionAction",
      "BotPluginApi.sendSessionAttachment",
      "BotPluginApi.scheduleSessionTurn",
      "BotPluginApi.unscheduleSessionTurnsByTag",
      "PluginHookContext.senderExternalId",
      "PluginAttachmentChannelHints.telegram",
      "PluginAttachmentChannelHints.slack",
      "AgentPromptSurfaceKind pi_main",
      "PluginRuntime.channel.reply.createReplyDispatcherWithTyping",
      "PluginRuntime.channel.reply.resolveHumanDelayConfig",
      "PluginRuntime.channel.reply.dispatchReplyFromConfig",
      "PluginRuntime.channel.reply.finalizeInboundContext",
      "PluginRuntime.channel.media.fetchRemoteMedia",
      "PluginRuntime.channel.session.resolveStorePath",
      "PluginRuntime.channel.session.recordInboundSession",
      "PluginRuntime.channel.inbound.runPreparedReply",
      "PluginRuntime.system.requestHeartbeatNow",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on plugin API and runtime aliases",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/captured-registration.test.ts",
      "src/plugins/runtime/index.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Flat plugin registration and broad runtime aliases remain available while plugins migrate to namespaced APIs and focused runtime methods.",
  },
  {
    code: "plugin-provider-manifest-compat-aliases",
    status: "deprecated",
    owner: "provider",
    introduced: MARKING_DATE,
    deprecated: MARKING_DATE,
    warningStarts: MARKING_DATE,
    removeAfter: DEFAULT_REMOVE_AFTER,
    replacement: "manifest-owned plugin kind/setup metadata and model catalog registration",
    docsPath: "/plugins/sdk-migration#compatibility-policy",
    surfaces: [
      "DefinePluginEntryOptions.kind",
      "SingleProviderPluginOptions.kind",
      "BotPluginDefinition.kind",
      "PluginPackageChannel.cliAddOptions",
      "ProviderPlugin.catalog",
      "ProviderPlugin.staticCatalog",
      "ProviderPlugin.suppressBuiltInModel",
      "ProviderPlugin.augmentModelCatalog",
      "ProviderBuiltInModelSuppressionContext",
    ],
    diagnostics: [
      "TypeScript @deprecated annotations on plugin manifest and provider catalog aliases",
      "plugin boundary report compatibility inventory",
    ],
    tests: [
      "src/plugins/contracts/package-manifest.contract.test.ts",
      "src/plugins/contracts/provider-catalog-deprecation.contract.test.ts",
      "src/plugins/compat/registry.test.ts",
    ],
    releaseNote:
      "Runtime plugin kind/setup metadata and provider catalog hooks remain available while plugins migrate ownership into manifests and catalog registrations.",
  },
] as const satisfies readonly PluginCompatRecord[];
